version: "3.8"

services:

  web:
    build: .
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    working_dir: /var/www
    command: npm run build

  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    ports:
      - 80:80
    depends_on:
      - web